---
title: "CTRP AUC ID Mapping"
output: html_notebook
---

```{r}
library(readxl)
exp_master <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/CTRP_AUC_datamap.xlsx", sheet = 1)
master_ccl <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/CTRP_AUC_datamap.xlsx", sheet = 2)
ccl_depmap <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/CTRP_AUC_datamap.xlsx", sheet = 3)
cpd_ctrp <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/CTRP_AUC_datamap.xlsx", sheet = 4)
```

```{r}
idx <- match(master_ccl$ccl_name, ccl_depmap$CellLineName)
match_depmap <- ccl_depmap[idx,]
master_ccl[["Depmap"]] <- match_depmap$BroadID
```

```{r}
idy <- match(exp_master$master_ccl_id, master_ccl$master_ccl_id)
match_cclid <- master_ccl[idy,]
exp_master[["Depmap_ID"]] <- match_cclid$Depmap
```

```{r}
AUC_CTRP <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/model_inputs.xlsx", sheet = 3)
idz <- match(AUC_CTRP$experiment_id, exp_master$experiment_id)
match_cell <- exp_master[idz,]
AUC_CTRP[["Depmap_ID"]] <- match_cell$Depmap_ID

ida <- match(AUC_CTRP$master_cpd_id, cpd_ctrp$master_cpd_id)
match_cpd <- cpd_ctrp[ida,]
AUC_CTRP[["Cpd_name"]] <- match_cpd$cpd_name
```

```{r}
AUC_data_long <- cbind(AUC_CTRP$Depmap_ID, AUC_CTRP$Cpd_name, AUC_CTRP$area_under_curve)
AUC_data_long <- as.data.frame(AUC_data_long)
colnames(AUC_data_long) <- c("Depmap_ID", "Cpd_name", "area_under_curve")
AUC_data_long <- na.omit(AUC_data_long)
AUC_data_long$area_under_curve <- as.numeric(AUC_data_long$area_under_curve)
head(AUC_data_long)
```

```{r}
remove.duplicates <- function(x){
  df_unique <- x %>%
    group_by(Depmap_ID, Cpd_name) %>%
    summarize(across(everything(), ~ mean(., na.rm = TRUE)), .groups = "drop")
  
  df_unique[is.na(df_unique)] <- 0
  return(df_unique)
}

AUC_data_long <- remove.duplicates(AUC_data_long)
AUC_data_long
```

```{r}
# Convert from long to wide format using reshape
AUC_data <- AUC_data_long %>%
  pivot_wider(names_from = Cpd_name, values_from = area_under_curve)

AUC_data[is.na(AUC_data)] <- 0
```

```{r}
CTRPv2_0_INFORMER_SET <- read_excel("~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/CTRPv2.0_2015_ctd2_ExpandedDataset/CTRPv2.0._INFORMER_SET.xlsx")
# Filter rows where inclusion_rationale contains "chromatin"
PTM_drugs <- CTRPv2_0_INFORMER_SET %>%
  filter(grepl("chromatin", inclusion_rationale))
```

```{r}
PTM_drug_AUC <- AUC_data[,PTM_drugs$cpd_name]
rownames(PTM_drug_AUC) <- AUC_data$Depmap_ID
```
```{r}
write.csv(PTM_drug_AUC, "~/University of Michigan Dropbox/Rupa Bhowmick/Rupa Bhowmick’s files/Home/Rupa_data/PTM_metabolite_Drug/Data/Model_data/PTM_drugs_AUC.csv")
```

